name: .NET Framework

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Clone
      uses: actions/checkout@v4

    - name: Restore
      run: msbuild -t:restore -p:RestoreLockedMode=true -m

    - name: Build
      run: msbuild -t:build -p:Configuration=Release -m

    - name: Move artifacts
      run: |
        New-Item upload -ItemType Directory -Force
        Copy-Item -Destination .\upload\ *\bin\Release\*.exe

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Trainers
        path: upload
        if-no-files-found: error
